package tmuxconf

import (
	"fmt"
	"os"
	"path/filepath"
)

// RecommendedConfig はツール制作者推奨の tmux 設定
var RecommendedConfig = `# muxflow recommended tmux configuration
# Generated by muxflow
# To restore original: cp ~/.tmux.conf.bak ~/.tmux.conf

unbind C-b
set -g prefix C-s

# マウス操作を有効にする
set-option -g mouse on

# === スクロール改善設定 ===
set -g history-limit 50000

# === ペインのデザイン設定 ===
set -g pane-border-style fg=cyan,bg=default
set -g pane-active-border-style fg=red,bg=default,bold
set -g pane-border-lines heavy

# ペインのタイトル表示（git ブランチ付き）
set -g pane-border-status top
set -g pane-border-format "#{?pane_active,#[fg=yellow#,bold],#[fg=cyan#,bold]} #P: #{pane_title} #[fg=yellow,bold][#(cd '#{pane_current_path}' && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '')]"

# アクティブペインをさらに強調
set -g window-active-style 'fg=terminal,bg=terminal'
set -g window-style 'fg=colour247,bg=colour236'

# === ステータスバー設定 ===
set -g status-position top
set -g status-justify left

# 【左側】セッション名
set -g status-left-length 20
set -g status-left '#[fg=white,bold]S: #S'

# 【右側】カレントパスと git ブランチ
set -g status-right-length 150
set -g status-right "#[fg=white,bold]#{pane_current_path} #[fg=yellow,bold](#(cd '#{pane_current_path}' && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '')) #[default]"

# ウィンドウリストのスタイル
setw -g window-status-format ' #I:#W#[fg=cyan]#(test -f ~/.claude_notification_#{session_name} && cat ~/.claude_notification_#{session_name} || echo "") '
setw -g window-status-current-format '#[fg=black,bg=yellow,bold] #I:#W#[fg=red,bold]#(test -f ~/.claude_notification_#{session_name} && cat ~/.claude_notification_#{session_name} || echo "") '

# vim キーバインドでペイン移動
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# vim キーバインドでペインリサイズ
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# ペイン分割
bind \\ split-window -h
bind - split-window -v

# 設定リロード
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# 全セッションで .zshrc を再読み込み
bind R run-shell 'tmux list-sessions -F "#{session_name}" | xargs -I {} tmux send-keys -t {} "source ~/.zshrc" Enter' \; display-message "Sourced .zshrc in all sessions!"

set -sg escape-time 1

# Claude Code 通知のクリア（セッション切り替え時）
set-hook -g client-session-changed 'run-shell "tmux set-option -t \"#{session_name}\" -u @claude_notification"'

bind s choose-tree -sZ -F "#{?@claude_notification,🔔,} #{session_windows} windows"
set -g focus-events on

# muxflow: PREFIX+m で起動
bind m new-window -n "muxflow" "muxflow"
`

// ConfigPath は ~/.tmux.conf のフルパスを返す
func ConfigPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".tmux.conf")
}

// BackupPath は ~/.tmux.conf.bak のフルパスを返す
func BackupPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".tmux.conf.bak")
}

// Exists は ~/.tmux.conf が存在するか確認する
func Exists() bool {
	_, err := os.Stat(ConfigPath())
	return err == nil
}

// BackupExists は ~/.tmux.conf.bak が存在するか確認する
func BackupExists() bool {
	_, err := os.Stat(BackupPath())
	return err == nil
}

// Apply は推奨設定を ~/.tmux.conf に書き込む。
// backup=true の場合は既存ファイルを ~/.tmux.conf.bak にバックアップしてから書き込む。
func Apply(backup bool) error {
	if backup && Exists() {
		if err := os.Rename(ConfigPath(), BackupPath()); err != nil {
			return fmt.Errorf("バックアップ失敗: %w", err)
		}
	}
	return os.WriteFile(ConfigPath(), []byte(RecommendedConfig), 0644)
}

// Restore は ~/.tmux.conf.bak を ~/.tmux.conf に復元する
func Restore() error {
	if !BackupExists() {
		return fmt.Errorf("バックアップが見つかりません: %s", BackupPath())
	}
	return os.Rename(BackupPath(), ConfigPath())
}
